#-------------------------------------------------------------------------------------------
# Copyright (c) 2026-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[build]
target = "./toolchains/x86_64-fenrir.json"

[unstable]
build-std = ["alloc", "core"]
build-std-features = ["compiler-builtins-mem"]
