#!/bin/sh

name=mlibc
version=6.3.1
revision=0
allow_network=yes

from_source="mlibc-headers"
deps="mlibc-headers"
hostdeps="binutils gcc"

configure() {
    cp -rpf "${source_dir}/." ./
    meson setup \
        build . \
        --cross-file="${base_dir}/toolchains/${JINX_ARCH}-fenrir.ini" \
        --prefix="${prefix}" \
        -Ddefault_library=static \
        -Dno_headers=true
}

build() {
    ninja -C build -j"${parallelism}"
}

package() {
    DESTDIR="${dest_dir}" ninja -C build install
}
