#-------------------------------------------------------------------------------------------
# Copyright (c) 2026-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

timeout: 0

/Leviathan
    protocol: limine
    path: boot():/boot/kernel
    module_path: boot():/modules/initramfs.tar