#-------------------------------------------------------------------------------------------
# Copyright (c) 2026-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[toolchain]
channel = "nightly-2026-01-01"
components = ["rust-src", "rustfmt", "clippy"]
