#!/bin/sh

name=mlibc-headers
version=0
revision=0

mlibc_commit='d5efaaaffcb7622429986edb835792ba7d612380'

tarball_url="https://github.com/managarm/mlibc/archive/${mlibc_commit}.tar.gz"
tarball_sha256="3c95737dde1a592bd08bb779b59a90b4ee9f57350a5614553815b1b6863e1005"

configure() {
    meson setup \
        headers-build "${source_dir}" \
        --cross-file="${base_dir}/toolchains/${JINX_ARCH}-fenrir.ini" \
        --prefix="${prefix}" \
        -Dheaders_only=true
}

build() {
    ninja -C headers-build -j"${parallelism}"
}

package() {
    DESTDIR="${dest_dir}" ninja -C headers-build install
}
