#-------------------------------------------------------------------------------------------
# Copyright (c) 2026-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

.SUFFIXES:

.PHONY: all 
all:
	RUSTFLAGS="-C relocation-model=static" cargo build

.PHONY: clean
clean:
	cargo clean

