#-------------------------------------------------------------------------------------------
# Copyright (c) 2026-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

src = ['src/main.c']

sources = files(src)

hello_world = executable('hello_world', sources: sources)
