#-------------------------------------------------------------------------------------------
# Copyright (c) 2026-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

src = ['src/main.c']

sources = files(src)
includes = include_directories('include')

hello_world = executable('hello_world', sources: sources, include_directories: includes)
