#-------------------------------------------------------------------------------------------
# Copyright (c) 2026-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

add_subdirectory(libraries/libc)

add_subdirectory(services/window_manager)

add_subdirectory(hello_world)
